import CourseList from "./components/CourseList";

export const metadata = {
  title: "CourseZone",
  description: "Generated by create next app",
};

const Page = () => {
  return <CourseList />;
};

export default Page;
